title: relevance.io
description: >
  Learn about the BigFix Relevance Language.
baseurl: ""
url: "https://relevance.io"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

collections:
  guide:
    output: true
  types:
    output: true

defaults:
  - scope:
      path: guide
    values:
      layout: guide
  - scope:
      path: reference
    values:
      layout: reference
